# Generated by Django 3.0.3 on 2020-09-04 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_auto_20200904_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='firm_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_firm', to='manager_app.Add_Firm'),
        ),
    ]
